package com.illumi.oms.model;

import java.util.Date;

import com.illumi.oms.common.Consts;
import com.jayqqaa12.jbase.jfinal.ext.model.EasyuiModel;
import com.jfinal.ext.plugin.tablebind.TableBind;
import com.jfinal.log.Logger;

/**
 * Generated by JFinal.
 */
@TableBind(tableName = "t_ip_pool")
public class IpPool extends  EasyuiModel<IpPool> {


	/**
	 *
	 */
	private static final long serialVersionUID = 8024688825037398020L;

	public static final IpPool me = new IpPool();

	private static final Logger LOG = Logger.getLogger(IpPool.class);
	
	public static IpPool dao = new IpPool();
}
