package com.illumi.oms.model;

import com.jayqqaa12.jbase.jfinal.ext.model.EasyuiModel;
import com.jfinal.ext.plugin.tablebind.TableBind;

/**
 * Generated by JFinal.
 */
@TableBind(tableName = "t_notice")
public class Notice extends  EasyuiModel<Notice> {


	/**
	 *
	 */
	
	private static final long serialVersionUID = 8024688825037398020L;

	public static final Notice me = new Notice();




}
