package com.illumi.oms.model;

import com.jayqqaa12.jbase.jfinal.ext.model.EasyuiModel;
import com.jfinal.ext.plugin.tablebind.TableBind;
import com.jfinal.log.Logger;

/**
 * Generated by JFinal.
 */
@TableBind(tableName = "t_user_address")
public class UserAddress extends  EasyuiModel<UserAddress> {


	/**
	 *
	 */
	private static final long serialVersionUID = 8024688825037398020L;

	public static final UserAddress me = new UserAddress();

	private static final Logger LOG = Logger.getLogger(UserAddress.class);
	
	public static UserAddress dao = new UserAddress();
}
